PYTHON ?= python3
VENV ?= .venv
ACTIVATE = . $(VENV)/bin/activate
ALEMBIC ?= alembic
UVICORN_APP ?= app.main:app
HOST ?= 0.0.0.0
PORT ?= 8000
MSG ?= describe schema change
REV ?= -1

.PHONY: help venv install run dev lint migrate revision downgrade current history

help:
	@echo "HealLink backend Make targets:"
	@echo "  make venv                  Create virtual environment"
	@echo "  make install               Install project dependencies"
	@echo "  make run                   Run FastAPI app"
	@echo "  make dev                   Run FastAPI app with reload"
	@echo "  make lint                  Run ruff checks"
	@echo "  make migrate               Apply migrations to latest revision"
	@echo "  make revision MSG='...'    Create new autogenerated migration"
	@echo "  make downgrade REV=-1      Roll back migration by revision"
	@echo "  make current               Show current migration revision"
	@echo "  make history               Show migration history"

venv:
	$(PYTHON) -m venv $(VENV)

install:
	$(ACTIVATE) && pip install -e .

run:
	$(ACTIVATE) && uvicorn $(UVICORN_APP) --host $(HOST) --port $(PORT)

dev:
	$(ACTIVATE) && uvicorn $(UVICORN_APP) --host $(HOST) --port $(PORT) --reload

lint:
	$(ACTIVATE) && ruff check app

migrate:
	$(ACTIVATE) && $(ALEMBIC) upgrade head

revision:
	$(ACTIVATE) && $(ALEMBIC) revision --autogenerate -m "$(MSG)"

downgrade:
	$(ACTIVATE) && $(ALEMBIC) downgrade $(REV)

current:
	$(ACTIVATE) && $(ALEMBIC) current

history:
	$(ACTIVATE) && $(ALEMBIC) history
