"""add_is_active_to_super_admins_and_officers_and_super_admin_id_to_refresh_tokens

Revision ID: 144211a14164
Revises: fc2b30473d3f
Create Date: 2026-06-03 00:56:26.179462
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144211a14164'
down_revision: Union[str, None] = 'fc2b30473d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('super_admin_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_super_admin_id'), 'refresh_tokens', ['super_admin_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'super_admins', ['super_admin_id'], ['id'])
    op.add_column('super_admins', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admins', 'is_active')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_super_admin_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'super_admin_id')
    op.drop_column('officers', 'is_active')
    # ### end Alembic commands ###
