"""provider_email

Revision ID: 54ef7c32c10f
Revises: 938504b901a6
Create Date: 2026-06-02 11:48:47.280127
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ef7c32c10f'
down_revision: Union[str, None] = '938504b901a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_action_tokens', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.alter_column('account_action_tokens', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_account_action_tokens_provider_id'), 'account_action_tokens', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'account_action_tokens', 'providers', ['provider_id'], ['id'])
    op.add_column('providers', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'is_verified')
    op.drop_constraint(None, 'account_action_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_account_action_tokens_provider_id'), table_name='account_action_tokens')
    op.alter_column('account_action_tokens', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('account_action_tokens', 'provider_id')
    # ### end Alembic commands ###
