"""reset_schema

Revision ID: 938504b901a6
Revises: 
Create Date: 2026-06-02 11:03:52.415177
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938504b901a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='patient', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('DOCTOR', 'CLINIC', 'DIAGNOSTIC_CENTER', name='providertype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('tin_number', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus'), server_default='pending', nullable=False),
    sa.Column('license_document_url', sa.String(length=500), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('average_rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['verified_by'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_license_number'), 'providers', ['license_number'], unique=False)
    op.create_index(op.f('ix_providers_location'), 'providers', ['location'], unique=False)
    op.create_index(op.f('ix_providers_provider_type'), 'providers', ['provider_type'], unique=False)
    op.create_index(op.f('ix_providers_tin_number'), 'providers', ['tin_number'], unique=False)
    op.create_table('account_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_CHANGE', name='accountactionpurpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_action_tokens_id'), 'account_action_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_account_action_tokens_patient_id'), 'account_action_tokens', ['patient_id'], unique=False)
    op.create_index(op.f('ix_account_action_tokens_purpose'), 'account_action_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_account_action_tokens_token_hash'), 'account_action_tokens', ['token_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_patient_id'), 'refresh_tokens', ['patient_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_catalog_id'), 'service_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_service_catalog_location'), 'service_catalog', ['location'], unique=False)
    op.create_index(op.f('ix_service_catalog_provider_id'), 'service_catalog', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_catalog_service_type'), 'service_catalog', ['service_type'], unique=False)
    op.create_table('provider_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='scheduletype'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_id', 'day_of_week', 'start_time', name='unique_provider_schedule_slot')
    )
    op.create_index(op.f('ix_provider_schedules_id'), 'provider_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_provider_id'), 'provider_schedules', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_service_id'), 'provider_schedules', ['service_id'], unique=False)
    op.create_table('service_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_slots_id'), 'service_slots', ['id'], unique=False)
    op.create_index(op.f('ix_service_slots_is_booked'), 'service_slots', ['is_booked'], unique=False)
    op.create_index(op.f('ix_service_slots_service_id'), 'service_slots', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_slots_starts_at'), 'service_slots', ['starts_at'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_of_id', sa.Integer(), nullable=True),
    sa.Column('continuation_appointment_id', sa.Integer(), nullable=True),
    sa.Column('appointment_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED', 'COMPLETED', 'NEEDS_RECHECK', 'FOLLOW_UP_BOOKED', 'CHECKED_IN', name='appointmentstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('provider_recheck_reason', sa.Text(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['continuation_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['follow_up_of_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['service_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_at'), 'appointments', ['appointment_at'], unique=False)
    op.create_index(op.f('ix_appointments_continuation_appointment_id'), 'appointments', ['continuation_appointment_id'], unique=False)
    op.create_index(op.f('ix_appointments_follow_up_of_id'), 'appointments', ['follow_up_of_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_table('diagnostic_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'COLLECTED', name='diagnosticresultstatus'), nullable=False),
    sa.Column('updated_by_provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_results_appointment_id'), 'diagnostic_results', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_diagnostic_results_id'), 'diagnostic_results', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'ADMIN', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('email_failed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_appointment_id'), 'notifications', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('tx_ref', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('chapa_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_payments_chapa_reference'), 'payments', ['chapa_reference'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_tx_ref'), 'payments', ['tx_ref'], unique=True)
    op.create_table('qr_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=6), nullable=False),
    sa.Column('qr_image_b64', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='qrcheckinstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['used_by_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_checkins_appointment_id'), 'qr_checkins', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_qr_checkins_card_number'), 'qr_checkins', ['card_number'], unique=False)
    op.create_index(op.f('ix_qr_checkins_id'), 'qr_checkins', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_appointment_id'), 'reviews', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_patient_id'), 'reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reviews_provider_id'), 'reviews', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_provider_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_patient_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_appointment_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_qr_checkins_id'), table_name='qr_checkins')
    op.drop_index(op.f('ix_qr_checkins_card_number'), table_name='qr_checkins')
    op.drop_index(op.f('ix_qr_checkins_appointment_id'), table_name='qr_checkins')
    op.drop_table('qr_checkins')
    op.drop_index(op.f('ix_payments_tx_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_chapa_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_appointment_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_diagnostic_results_id'), table_name='diagnostic_results')
    op.drop_index(op.f('ix_diagnostic_results_appointment_id'), table_name='diagnostic_results')
    op.drop_table('diagnostic_results')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_follow_up_of_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_continuation_appointment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_at'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_service_slots_starts_at'), table_name='service_slots')
    op.drop_index(op.f('ix_service_slots_service_id'), table_name='service_slots')
    op.drop_index(op.f('ix_service_slots_is_booked'), table_name='service_slots')
    op.drop_index(op.f('ix_service_slots_id'), table_name='service_slots')
    op.drop_table('service_slots')
    op.drop_index(op.f('ix_provider_schedules_service_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_provider_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_id'), table_name='provider_schedules')
    op.drop_table('provider_schedules')
    op.drop_index(op.f('ix_service_catalog_service_type'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_provider_id'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_location'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_id'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_patient_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_account_action_tokens_token_hash'), table_name='account_action_tokens')
    op.drop_index(op.f('ix_account_action_tokens_purpose'), table_name='account_action_tokens')
    op.drop_index(op.f('ix_account_action_tokens_patient_id'), table_name='account_action_tokens')
    op.drop_index(op.f('ix_account_action_tokens_id'), table_name='account_action_tokens')
    op.drop_table('account_action_tokens')
    op.drop_index(op.f('ix_providers_tin_number'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_type'), table_name='providers')
    op.drop_index(op.f('ix_providers_location'), table_name='providers')
    op.drop_index(op.f('ix_providers_license_number'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_health_events_id'), table_name='health_events')
    op.drop_table('health_events')
    # ### end Alembic commands ###
