"""add_officer_id_to_refresh_tokens

Revision ID: 965910d2d883
Revises: 144211a14164
Create Date: 2026-06-03 01:13:43.696609
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965910d2d883'
down_revision: Union[str, None] = '144211a14164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_officer_id'), 'refresh_tokens', ['officer_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'officers', ['officer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_officer_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'officer_id')
    # ### end Alembic commands ###
