"""add_qr_checkin_feature

Revision ID: add_qr_checkin
Revises: b535557a2e1e
Create Date: 2026-06-01 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_qr_checkin'
down_revision: Union[str, None] = 'b535557a2e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type for qr_checkin_status if not exists
    qr_checkin_status_enum = sa.Enum('active', 'used', 'expired', name='qrcheckinstatus')
    qr_checkin_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Create qr_checkins table
    op.create_table('qr_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=6), nullable=False),
    sa.Column('qr_image_b64', sa.Text(), nullable=False),
    sa.Column('status', qr_checkin_status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['used_by_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_checkins_appointment_id'), 'qr_checkins', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_qr_checkins_card_number'), 'qr_checkins', ['card_number'], unique=False)
    op.create_index(op.f('ix_qr_checkins_id'), 'qr_checkins', ['id'], unique=False)
    
    # Add CHECKED_IN to appointmentstatus enum
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'checked_in'")
    
    # Add check_in_time column to appointments table
    op.add_column('appointments', sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove check_in_time column from appointments table
    op.drop_column('appointments', 'check_in_time')
    
    # Note: Removing enum values is not directly supported in PostgreSQL
    # The CHECKED_IN value will remain in the enum but won't be used
    
    # Drop qr_checkins table
    op.drop_index(op.f('ix_qr_checkins_id'), table_name='qr_checkins')
    op.drop_index(op.f('ix_qr_checkins_card_number'), table_name='qr_checkins')
    op.drop_index(op.f('ix_qr_checkins_appointment_id'), table_name='qr_checkins')
    op.drop_table('qr_checkins')
    
    # Drop enum type
    sa.Enum(name='qrcheckinstatus').drop(op.get_bind())
    
    # ### end Alembic commands ###
