"""add_reviews_and_ratings

Revision ID: add_reviews_and_ratings
Revises: add_diagnostic_results
Create Date: 2026-06-01 12:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_reviews_and_ratings'
down_revision: Union[str, None] = 'add_diagnostic_results'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create reviews table
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_appointment_id'), 'reviews', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_patient_id'), 'reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reviews_provider_id'), 'reviews', ['provider_id'], unique=False)
    
    # Add rating columns to providers table
    op.add_column('providers', sa.Column('average_rating', sa.Float(), nullable=False, server_default='0'))
    op.add_column('providers', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove rating columns from providers table
    op.drop_column('providers', 'review_count')
    op.drop_column('providers', 'average_rating')
    
    # Drop reviews table
    op.drop_index(op.f('ix_reviews_provider_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_patient_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_appointment_id'), table_name='reviews')
    op.drop_table('reviews')
    
    # ### end Alembic commands ###
