"""add_provider_schedule

Revision ID: add_provider_schedule
Revises: add_qr_checkin
Create Date: 2026-06-01 21:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_provider_schedule'
down_revision: Union[str, None] = 'add_qr_checkin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type for schedule_type if not exists
    schedule_type_enum = sa.Enum('daily', 'weekly', 'custom', name='scheduletype')
    schedule_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Create provider_schedules table
    op.create_table('provider_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', schedule_type_enum, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_id', 'day_of_week', 'start_time', name='unique_provider_schedule_slot')
    )
    op.create_index(op.f('ix_provider_schedules_id'), 'provider_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_provider_id'), 'provider_schedules', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_service_id'), 'provider_schedules', ['service_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop provider_schedules table
    op.drop_index(op.f('ix_provider_schedules_service_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_provider_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_id'), table_name='provider_schedules')
    op.drop_table('provider_schedules')
    
    # Drop enum type
    sa.Enum(name='scheduletype').drop(op.get_bind())
    
    # ### end Alembic commands ###
