"""add_provider_password

Revision ID: add_provider_password
Revises: add_reviews_and_ratings
Create Date: 2026-06-01 13:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_provider_password'
down_revision: Union[str, None] = 'add_reviews_and_ratings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add hashed_password column to providers table
    # For existing providers, we'll need to set a default or handle migration separately
    op.add_column('providers', sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=''))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove hashed_password column from providers table
    op.drop_column('providers', 'hashed_password')
    
    # ### end Alembic commands ###
