"""add_super_admins_and_officers_tables

Revision ID: fc2b30473d3f
Revises: 20260602_profile_pic
Create Date: 2026-06-03 00:42:03.396602
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2b30473d3f'
down_revision: Union[str, None] = '20260602_profile_pic'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_badge_number'), 'officers', ['badge_number'], unique=True)
    op.create_index(op.f('ix_officers_email'), 'officers', ['email'], unique=True)
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_email'), table_name='officers')
    op.drop_index(op.f('ix_officers_badge_number'), table_name='officers')
    op.drop_table('officers')
    # ### end Alembic commands ###
